# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MeiTunHD' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MeiTunHD

pod 'YYModel'
pod 'Masonry'
pod 'SDWebImage'
pod 'FMDB'


end
